import pubnub from "../../config/pubnub";
import RoomPage from "./RoomPage";
import { Metadata } from "next";

export async function generateMetadata(): Promise<Metadata> {
    return {
        title: 'Monopoli Lemao | Room List',
        description: 'Generated by Next.js'
    }
}

export default function Page() {
    // pubnub settings
    const pubnubSetting = {
      subscribeKey: process.env.PUBNUB_SUB_KEY,
      publishKey: process.env.PUBNUB_PUB_KEY,
      userId: process.env.PUBNUB_UUID
    }

    return <RoomPage pubnubSetting={pubnubSetting} />
}