import RoomPage from "./RoomPage";
import { Metadata } from "next";

export async function generateMetadata(): Promise<Metadata> {
    return {
        title: 'Monopoli Lemao | Room List',
        description: 'Generated by Next.js'
    }
}

export default function Page() {

    return <RoomPage />
}