import GamePage from "./GamePage";
import { Metadata } from "next";

export async function generateMetadata(): Promise<Metadata> {
    return {
        title: 'Monopoli Lemao | Game Room',
        description: 'Generated by Next.js'
    }
}

export default function Page() {

    return <GamePage />
}