import { MiscProvider } from '../context/MiscContext'
import './globals.css'
import { Metadata, Viewport } from 'next'

export async function generateMetadata(): Promise<Metadata> {
    return {
        title: 'Monopoli Lemao',
        description: 'Generated by Next.js'
    }
}

export const viewport: Viewport = {
  initialScale: 1,
  width: 'device-width'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <MiscProvider>
        <body>{children}</body>
      </MiscProvider>
    </html>
  )
}
