import HomePage from "./home/HomePage";
import { Metadata } from "next";

export async function generateMetadata(): Promise<Metadata> {
    return {
        title: 'Monopoli Lemao',
        description: 'Generated by Next.js'
    }
}

export default function Page() {

    return <HomePage />
}